'use strict';
const crypto = require('crypto');
const transitions = { source_ingested: ['editing'], editing: ['review_pending', 'render_queued'], review_pending: ['approved', 'rejected'], rejected: ['editing'], approved: ['render_queued'], render_queued: ['rendering'], rendering: ['rendered', 'failed'], rendered: ['publish_pending', 'exported'], publish_pending: ['published', 'failed'], failed: ['render_queued', 'publish_pending'], published: [], exported: [] };
const perms = { viewer: ['read'], editor: ['read', 'edit'], reviewer: ['read', 'review'], publisher: ['read', 'publish'], admin: ['read', 'edit', 'review', 'publish', 'configure'] };
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.keys(v).sort().reduce((out,key)=>{out[key]=canonical(v[key]);return out;},{}):v;
const hash = v => crypto.createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');
function requireScope(actor, tenantId, action) { if (!actor || actor.tenantId !== tenantId) throw new Error('tenant_scope_denied'); if (!(perms[actor.role] || []).includes(action)) throw new Error('role_scope_denied'); }
function validateProject(input) { for (const f of ['title', 'ownerId', 'brandVersion', 'timeline', 'assets', 'disclosurePolicy']) if (!input[f] || (Array.isArray(input[f]) && !input[f].length)) throw new Error(`missing_${f}`);const ids=new Set(input.assets.map(a=>String(a.id)));if(ids.size!==input.assets.length)throw new Error('duplicate_asset_id');if(input.assets.some(a => !a.id || !/^(s3|gs|https):\/\//.test(a.objectUri||'') || !/^[a-f0-9]{64}$/i.test(a.checksum||'') || !a.rights?.license || !['granted','not_required'].includes(a.rights?.consentStatus) || !a.rights?.provenanceUri)) throw new Error('asset_rights_provenance_uri_and_checksum_required'); if (input.timeline.some(t => !ids.has(String(t.assetId)) || !Number.isSafeInteger(t.startMs) || !Number.isSafeInteger(t.endMs) || t.startMs < 0 || t.endMs <= t.startMs)) throw new Error('invalid_timeline'); if (typeof input.disclosurePolicy.aiDisclosure !== 'boolean' || !['required','optional','prohibited'].includes(input.disclosurePolicy.watermark)) throw new Error('invalid_disclosure_policy'); const normalized={...input,title:String(input.title).trim(),ownerId:String(input.ownerId),assets:input.assets.map(a=>({...a,id:String(a.id)})),timeline:input.timeline.map(t=>({...t,assetId:String(t.assetId)}))};return { ...normalized, projectHash: hash(normalized), state: 'source_ingested' }; }
function transition(current, target, ctx = {}) { if (!(transitions[current] || []).includes(target)) throw new Error('invalid_transition'); if (target === 'approved' && (!ctx.reviewerId || ctx.reviewerId === ctx.ownerId || !ctx.moderationAccepted || !ctx.rightsAccepted)) throw new Error('independent_rights_moderation_approval_required'); if (target === 'published' && (!ctx.publisherApprovalId || !ctx.providerReceiptId)) throw new Error('publish_approval_and_receipt_required'); return target; }
function delivery(provider, operation, payload, idempotencyKey, receipt, usage = {}) { if (!provider || !operation || !idempotencyKey) throw new Error('typed_delivery_identity_required');if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error('invalid_delivery_payload');for(const field of ['inputUnits','outputUnits','costMicros'])if(usage[field]!==undefined&&(!Number.isSafeInteger(usage[field])||usage[field]<0))throw new Error(`invalid_usage_${field}`); const payloadHash = hash(payload); if (receipt && receipt.payloadHash !== payloadHash) throw new Error('receipt_payload_mismatch'); return { provider, operation, payloadHash, idempotencyKey, usage, state: receipt ? 'confirmed' : 'queued', receipt: receipt || null }; }
function evaluate(result, limits) { const scoreNames=['quality','layoutScore','accessibility','brandScore','translationScore'];for(const name of scoreNames)if(!Number.isFinite(result[name])||result[name]<0||result[name]>1||!Number.isFinite(limits[name])||limits[name]<0||limits[name]>1)throw new Error(`invalid_${name}`);if(!Number.isFinite(result.timingErrorMs)||result.timingErrorMs<0||!Number.isFinite(limits.timingErrorMs)||limits.timingErrorMs<0)throw new Error('invalid_timingErrorMs');if(typeof result.deterministicExport!=='boolean')throw new Error('invalid_deterministicExport');const failures = []; if (result.quality < limits.quality) failures.push('quality'); if (result.timingErrorMs > limits.timingErrorMs) failures.push('timing'); if (result.layoutScore < limits.layoutScore) failures.push('layout'); if (result.accessibility < limits.accessibility) failures.push('accessibility'); if (result.brandScore < limits.brandScore) failures.push('brand'); if (result.translationScore < limits.translationScore) failures.push('multilingual'); if (!result.deterministicExport) failures.push('deterministic_export'); return { accepted: !failures.length, failures, resultHash: hash({ result, limits }) }; }
module.exports = { hash, requireScope, validateProject, transition, delivery, evaluate };
